name: schedule_test

on:
  schedule:
    - cron: "0 0 * * FRI"
    - cron: "0 12 * * MON"

jobs:
  schedule:
    runs-on: ubuntu-24.04
    steps:
      - name: Saludar
        run: echo "Hoy es Viernes!!!!"