name: Test

on:
  push:
    branches: [main]
    
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Aviso
        run: echo "GitHub Actions"

      - name: Ver Fecha
        run: date

      - name: Ver Archivos
        run: ls -la

  repo_files:
    runs-on: ubuntu-24.04
    steps:
      - name: Descargar Código
        uses: actions/checkout@v6

      - name: Ver Archivos
        run: ls -la

